/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'
import gsap from 'gsap'

import Room from './Room'
import Logo from './Logo'
import SubjectArea from './SubjectArea'
import ResearchArea from './ResearchArea'
import CommunityServiceArea from './CommunityServiceArea'
import BookArea from './BookArea.jsx'
import TvArea from './tv area/TvArea.jsx'
import useMainStore from '../store/useMainStore.js'
import { addVector3 } from '../utils/index.js'
import { ControlsContext } from '../context/ControlsContext.jsx'

const Lab = (props) => {
  const { nodes, materials } = useGLTF(process.env.REACT_APP_MODEL_URL)

  // get the state and setter from the store
  const focusTarget = useMainStore.useFocusTarget()
  const cameraPosition = useMainStore.useCameraPosition()
  const controlsTargetOffset = useMainStore.useControlsTargetOffset()

  const controlsTarget = addVector3(cameraPosition, controlsTargetOffset)

  const { controls } = React.useContext(ControlsContext)

  const { camera } = useThree()

  React.useEffect(() => {
    if (controls.current) {
      if (focusTarget !== null) {
        // disable rotate
        controls.current.enableRotate = false

        // animate camera to focus target
        gsap.to(controls.current.target, {duration: 1, ease: 'power4.inOut', x: controlsTarget[0], y: controlsTarget[1], z: controlsTarget[2]})
        gsap.to(camera.position, {duration: 1, ease: 'power4.inOut', x: cameraPosition[0], y: cameraPosition[1], z: cameraPosition[2]})
        
      } else {
        // enable rotate and set rotate speed back to default
        controls.current.enableRotate = true
        controls.current.rotateSpeed = -.5

        // animate back camera to original position 
        gsap.to(camera.position, {duration: 1, x: cameraPosition[0], y: cameraPosition[1], z: cameraPosition[2]})
        gsap.to(controls.current.target, {duration: 1, x: controlsTarget[0], y: controlsTarget[1], z: controlsTarget[2]})
      }
    }

  }, [focusTarget, cameraPosition, controlsTarget])
  return (
    <group {...props} dispose={null}>
      <Room nodes={nodes} materials={materials} />
      <Logo nodes={nodes} materials={materials} />
      <TvArea nodes={nodes} materials={materials} />
      <SubjectArea nodes={nodes} materials={materials} />
      <ResearchArea nodes={nodes} materials={materials} />
      <CommunityServiceArea nodes={nodes} materials={materials} />
      <BookArea nodes={nodes} materials={materials} />
    </group>
  )
}

useGLTF.preload(process.env.REACT_APP_MODEL_URL)

export default Lab